"""Synchro-compatible volume export and peak-hour identification."""

from __future__ import annotations

from typing import Optional

import pandas as pd


# ---------------------------------------------------------------------------
# Peak-hour identification
# ---------------------------------------------------------------------------

PEAK_WINDOWS = {
    "AM": (6, 11),   # 6:00 – 10:59
    "PM": (14, 19),  # 14:00 – 18:59
}


def identify_peak_hour(
    averaged_df: pd.DataFrame,
    period: str = "AM",
    interval_col: str = "interval",
    rolling_hours: float = 1.0,
    interval_minutes: int = 15,
) -> tuple[str, str]:
    """Find the peak hour start and end within a peak period.

    Uses a sliding sum over `rolling_hours` of data summed across all
    approach columns to locate the highest-volume window.

    Args:
        averaged_df: 96-row DataFrame with 'interval' column (HH:MM) and approach cols.
        period: 'AM' or 'PM'.
        interval_col: Name of the time-interval column.
        rolling_hours: Window length in hours (default 1.0).
        interval_minutes: Duration of each row in minutes.

    Returns:
        (start_time, end_time) as HH:MM strings.
    """
    period = period.upper()
    if period not in PEAK_WINDOWS:
        raise ValueError(f"period must be one of {list(PEAK_WINDOWS)}, got '{period}'")

    window_start_h, window_end_h = PEAK_WINDOWS[period]
    rolling_steps = int(rolling_hours * 60 / interval_minutes)

    df = averaged_df.copy()
    df["_hour"] = df[interval_col].str.split(":").str[0].astype(int)

    peak_mask = (df["_hour"] >= window_start_h) & (df["_hour"] < window_end_h)
    window_df = df[peak_mask].copy().reset_index(drop=True)

    approach_cols = [c for c in averaged_df.columns if c not in (interval_col, "_hour")]
    if not approach_cols:
        return (f"{window_start_h:02d}:00", f"{window_start_h + 1:02d}:00")

    window_df["_total"] = window_df[approach_cols].sum(axis=1)
    rolling_sum = window_df["_total"].rolling(rolling_steps, min_periods=rolling_steps).sum()

    if rolling_sum.isna().all():
        return (f"{window_start_h:02d}:00", f"{window_start_h + 1:02d}:00")

    peak_end_idx = rolling_sum.idxmax()
    peak_start_idx = max(0, peak_end_idx - rolling_steps + 1)

    start_str = window_df.loc[peak_start_idx, interval_col]
    end_str = window_df.loc[peak_end_idx, interval_col]

    # Advance end by one interval to represent the exclusive boundary
    end_dt = pd.to_datetime(end_str, format="%H:%M") + pd.Timedelta(minutes=interval_minutes)
    end_str = end_dt.strftime("%H:%M")

    return start_str, end_str


# ---------------------------------------------------------------------------
# Synchro export
# ---------------------------------------------------------------------------

SYNCHRO_HEADER_COMMENT = (
    "# Synchro Volume Import File\n"
    "# Generated by Signal Detector QC AI\n"
    "# Format: INTID, Time, <Approach Movements>\n"
)


def export_synchro_volumes(
    averaged_df: pd.DataFrame,
    intersection_id: str,
    adjustment_factors: Optional[dict[str, float]] = None,
    interval_col: str = "interval",
    output_path: Optional[str] = None,
    include_factors: bool = True,
) -> pd.DataFrame:
    """Create a Synchro-compatible volume DataFrame (and optionally save to CSV).

    Output columns:
        INTID | Time | <movement_1> | <movement_2> | ...

    Args:
        averaged_df: Output of `average_approach_volumes`.
        intersection_id: Synchro intersection ID string.
        adjustment_factors: Dict of {movement: factor} for transparency comment.
        interval_col: Name of the time-interval column in averaged_df.
        output_path: If provided, write the file to this path.
        include_factors: Prepend adjustment-factor metadata rows.

    Returns:
        Synchro-ready DataFrame.
    """
    approach_cols = [c for c in averaged_df.columns if c != interval_col]

    out = averaged_df[[interval_col] + approach_cols].copy()
    out.insert(0, "INTID", intersection_id)
    out = out.rename(columns={interval_col: "Time"})

    # Round volumes to nearest integer (Synchro expects whole vehicles)
    for col in approach_cols:
        out[col] = out[col].round(0).astype(int)

    if output_path:
        with open(output_path, "w") as fh:
            fh.write(SYNCHRO_HEADER_COMMENT)
            if include_factors and adjustment_factors:
                fh.write("# Adjustment Factors (actual/usable detectors):\n")
                for mvt, factor in adjustment_factors.items():
                    fh.write(f"#   {mvt}: {factor:.3f}\n")
            fh.write("#\n")
        out.to_csv(output_path, mode="a", index=False)

    return out


def export_network_synchro(
    network_results: dict[str, tuple[pd.DataFrame, dict[str, float]]],
    intersection_map: Optional[dict[str, str]] = None,
    output_path: Optional[str] = None,
    interval_col: str = "interval",
) -> pd.DataFrame:
    """Combine multiple intersections into a single network Synchro file.

    Args:
        network_results: {kits_id: (averaged_df, adjustment_factors)}
        intersection_map: {kits_id: synchro_id} mapping (identity if None).
        output_path: Optional path to save the combined CSV.

    Returns:
        Combined DataFrame with all intersections stacked vertically.
    """
    frames: list[pd.DataFrame] = []
    for kits_id, (avg_df, factors) in network_results.items():
        synchro_id = (intersection_map or {}).get(kits_id, kits_id)
        df_out = export_synchro_volumes(
            avg_df, synchro_id, factors, interval_col=interval_col
        )
        frames.append(df_out)

    if not frames:
        return pd.DataFrame()

    combined = pd.concat(frames, ignore_index=True)

    if output_path:
        with open(output_path, "w") as fh:
            fh.write(SYNCHRO_HEADER_COMMENT)
        combined.to_csv(output_path, mode="a", index=False)

    return combined


def compare_with_historical(
    current_df: pd.DataFrame,
    historical_df: pd.DataFrame,
    warn_pct: float = 20.0,
    critical_pct: float = 50.0,
    intid_col: str = "INTID",
    time_col: str = "Time",
) -> pd.DataFrame:
    """Compare current Synchro volumes against a historical baseline.

    Returns a DataFrame of flagged movements with pct change and severity.
    """
    approach_cols = [
        c for c in current_df.columns if c not in (intid_col, time_col)
    ]

    records = []
    for intid in current_df[intid_col].unique():
        curr_int = current_df[current_df[intid_col] == intid]
        hist_int = historical_df[historical_df[intid_col] == intid]

        if hist_int.empty:
            continue

        for app in approach_cols:
            if app not in curr_int.columns or app not in hist_int.columns:
                continue
            curr_total = pd.to_numeric(curr_int[app], errors="coerce").sum()
            hist_total = pd.to_numeric(hist_int[app], errors="coerce").sum()

            if hist_total == 0:
                continue

            pct_change = (curr_total - hist_total) / hist_total * 100

            if abs(pct_change) >= critical_pct:
                severity = "critical"
            elif abs(pct_change) >= warn_pct:
                severity = "warning"
            else:
                continue

            records.append(
                {
                    "INTID": intid,
                    "approach": app,
                    "current_daily_vol": round(curr_total, 0),
                    "historical_daily_vol": round(hist_total, 0),
                    "pct_change": round(pct_change, 1),
                    "severity": severity,
                }
            )

    return pd.DataFrame(records)
